convenienct dependency check for many packages getting removed

diff --git a/pacui b/pacui
--- a/pacui
+++ b/pacui
@@ -291,15 +291,75 @@ function func_r
             fi
             ' --preview-window=right:50%:wrap --header="TAB key to (un)select. ENTER key to remove. ESC to quit." --prompt='Enter string to filter list > ' | awk '{print $1}' )
 
-        # $pkg contains package names below each other, but we need a list (in 1 line, space separated):
-        pkg_remove=$(echo $pkg | paste -sd " ")
-
-        if [[ -n $pkg ]]                                                             # check, whether file is non zero-size
+        if [[ -n $pkg ]]                                                             # check, whether file is non zero-size. this happens when fzf is quit with CTRL+C.
         then
-            sudo pacman -Rsn $pkg_remove --color always
+
+            # $pkg contains package names below each other, but we need a list (in 1 line, space separated):
+            pkg_remove=$(echo $pkg | paste -sd " ")
+
+            # wrap the "sudo pacman -Rns" command in an if-statement, which checks, whether the removal of packages works. the removal of packages does not work, if the user tries to remove a dependency.
+            # the failure of "sudo pacman -Rns" is especially annoying, if many packages has been chose for removal and 1 package is a dependency. by default, the list of pacakges (which are supposed to be removed) is NOT saved!
+            # "sudo pacman -Rsn $pkg_remove --color always" always gets executed!
+            if ! ( sudo pacman -Rsn $pkg_remove --color always )
+            then
+
+                # continue here only if "sudo pacman -Rns" has failed:
+                # 1. save list of packages to backup file.
+                echo $pkg_remove | tr " " "\n" > /tmp/pacui-remove-backup
+
+                # 2. Print error message. the user can read all error messages 8of pacman) and decide what to do next.
+                echo
+                echo "Package removal failed because a dependency was selected. "
+                echo "Press ENTER to try again or CTRL+C to quit."
+                read
+
+                # 3. try again with a limited list of packages in fzf. this loop is dependent on the /tmp/pacui-remove-backup file!
+                while [[ -e /tmp/pacui-remove-backup ]]
+                do
+
+                    local {pkg,pkg_remove}                                           # declare local variables
+
+                    # fzf lets you search and select the given list in a fast way. the "-m" flags makes it possible to select multiple list items.
+                    pkg=$( cat /tmp/pacui-remove-backup | fzf-tmux -m -e +s -i --query="$input2" --cycle --reverse --margin=4%,1%,1%,2% --inline-info --preview '
+                        if ( pacman -Qq {1} &>/dev/null )                            # check, if selected line is a locally installed package
+                        then
+                            pacman -Qi {1} --color always
+                        else
+                            echo -e "\e[1m{1} group has the following members: \e[0m"
+                            pacman -Sgq {1}
+                        fi
+                        ' --preview-window=right:50%:wrap --header="TAB key to (un)select. ENTER key to remove. ESC to quit." --prompt='Enter string to filter list > ' | awk '{print $1}' )
+
+                    if [[ -n $pkg ]]                                                 # check, whether file is non zero-size. this happens when fzf is quit with CTRL+C.
+                    then
+
+                        # $pkg contains package names below each other, but we need a list (in 1 line, space separated):
+                        pkg_remove=$(echo $pkg | paste -sd " ")
+
+                        # 
+                        if ! ( sudo pacman -Rsn $pkg_remove --color always )         # the "sudo pacman -Rsn" command is always executed!
+                        then
+                            # continue here only if "sudo pacman -Rns" has failed:
+                            # a) save list of packages to backup file.
+                            echo $pkg_remove | tr " " "\n" > /tmp/pacui-remove-backup
+
+                            # b) Print error message. the user can read all error messages (of pacman) and decide what to do next.
+                            echo
+                            echo "Package removal failed because a dependency was selected. "
+                            echo "Press ENTER to try again or CTRL+C to quit."
+                            read
+                        else
+                            # removing the /tmp/pacui-remove-backup file quits the loop
+                            rm /tmp/pacui-remove-backup
+                        fi
+
+                    fi
+
+                done
+
+            fi
         fi
 }
-
 
 
 function func_t
@@ -1219,7 +1279,7 @@ function func_h
             if  [[ ! -e /tmp/pacui-help ]]
             then
 
-                # this "heredoc" command pushes all the following lines into "cat" (and "cat pushed it to file /tmp/pacui-help) until a line with "EOF" is encountered
+                # this "heredoc" command pushes all the following lines into "cat" (and "cat pushed it to file /tmp/pacui-help) until a line containing the "EOF" keyword is encountered
                 cat > /tmp/pacui-help <<- "EOF"
 
 \e[1mWelcome to PacUIs Help Page
@@ -1512,7 +1572,7 @@ If you want to exit this mode without installing any packages, simply press CTRL
 
 Press "q" to quit this Help Page.
 
-                EOF
+EOF
 
             fi
 
