disable strict mode

diff --git a/pacui b/pacui
--- a/pacui
+++ b/pacui
@@ -27,10 +27,12 @@
 #  \e[0m         \033[0m                                                            # non-colored, non-bold text without background color  ( \033[0m has to be used in "awk")
 #  \e[1m         \033[1m                                                            # bold text  ( \033[1m has to be used in "awk")
 
-# use unofficial strict mode in order to make bash behave like modern programming languages. this should only be used for development:
-set -e                                                                              # exit script immediately, if any command exits with non-zero error code
-set -u                                                                              # only allow previously defined variables
-set -o pipefail                                                                     # if one command in a pipe fails, all fail (this is not default behavior!)
+# use unofficial strict mode in order to make bash behave like modern programming languages.
+# this should only be used for development.
+# ATTENTION: in order to complete this script in strict mode, EVERY command, which can fail with an error, should be called like this: "if ( <command> ); then echo ''; fi"
+#set -e                                                                              # exit script immediately, if any command exits with non-zero error code
+#set -u                                                                              # only allow previously defined variables
+#set -o pipefail                                                                     # if one command in a pipe fails, all fail (this is not default behavior!)
 
 
 
@@ -236,10 +238,8 @@ function func_m
         then
             # bugfix #4: use if-statement.
             # "yaourt -Qdt" exists with error code 1 when orphans are not removed (this is the default setting). because of unofficial strict bash mode, pacui also exits immediately with error code 1.
-            if ( yaourt -Qdt )                                                      # always execute "yaourt -Qdt" no matter what happens.
-            then
-                echo ""
-            fi
+            yaourt -Qdt
+            echo ""
 
         else                                                                        # this is the case, when tirzen, pacaur, pikaur, or no AUR helper is installed.
 
@@ -267,7 +267,7 @@ function func_m
 
 
         echo " sudo pacdiff ..."
-        set +u                                                                      # temporarily disable strict mode for environment variables
+        #set +u                                                                      # temporarily disable strict mode for environment variables
 
         if [[ -n $DIFFPROG ]]                                                       # this if-condition avoids error message when $DIFFPROG is not set/empty
         then
@@ -277,7 +277,7 @@ function func_m
             sudo DIFFPROG="pacui --diff" pacdiff
         fi
 
-        set -u
+        #set -u
         echo ""
 
 
@@ -901,7 +901,7 @@ function func_b
 
         if [[ -e /usr/bin/pacaur ]]                                                 # checks, whether file "pacaur" exists, i.e. pacaur is installed
         then
-            set +u                                                                  # temporarily disable strict mode for environment variables
+            #set +u                                                                  # temporarily disable strict mode for environment variables
 
             # the cache location of pacaur is important for downgrading packages installed from the AUR or reinstalling removed packages from the AUR:
             if [[ -z $AURDEST ]]                                                    # $AURDEST is environment variable for changing pacaur's default cache directory. check, if "AURDEST" variable is empty
@@ -911,7 +911,7 @@ function func_b
                 cachePACAUR="$AURDEST"
             fi
 
-            set -u
+            #set -u
         fi
 
 
@@ -1222,10 +1222,10 @@ function func_f
 
 
                 # 3. start NTP daemon and set system clock
-                # 4. wait for 60 seconds (maximum time needed for system clock to set to new time)
+                # 4. wait for 30 seconds (maximum time needed for system clock to set to new time)
                 # 5. write time from system clock to hardware clock
                 echo " setting clock (which can take a while) ..."
-                sudo ntpd -qg && sleep 60 && sudo hwclock -w
+                sudo ntpd -qg && sleep 30 && sudo hwclock -w
                 echo ""
 
             fi
@@ -1233,7 +1233,7 @@ function func_f
 
             # remove gnupg including all keys
             echo " sudo rm -r /etc/pacman.d/gnupg ..."
-            sudo rm -r /etc/pacman.d/gnupg &>/dev/null
+            sudo rm -r /etc/pacman.d/gnupg
             echo ""
 
 
@@ -1262,7 +1262,7 @@ function func_f
             echo ""
 
 
-            set +u
+            #set +u
 
             if [[ -e $HOME/.gnupg/gpg.conf ]]                                       # check, whether file $HOME/.gnupg/gpg.conf exists
             then
@@ -1282,7 +1282,7 @@ function func_f
                 fi
             fi
 
-            set -u
+            #set -u
 
 
             echo " cleaning pacman cache ..."
@@ -1324,7 +1324,7 @@ function func_c
         # this is the normal syntax for "trap" command:
         trap "unlink ${pacui_config}" EXIT
 
-        set +u
+        #set +u
 
         # if file /etc/default/tlp exists, push string "/etc/default/tlp              Configure power management." into ${pacui_config} file. there are enough spaces added to avoid users seeing file/folder description:
         [[ -e /etc/default/tlp ]]                       && echo -e "/etc/default/tlp                                                                                                                                                                                                                                                 Configure power management in file:" >> ${pacui_config}
@@ -1389,7 +1389,7 @@ function func_c
         [[ -e /boot/EFI/CLOVER/config.plist ]]          && echo -e "\e[31m/boot/EFI/CLOVER/config.plist                                                                                                                                                                                                                              Configure Clover boot loader in file:\e[0m" >> ${pacui_config}
         [[ -e /boot/syslinux/syslinux.cfg ]]            && echo -e "\e[31m/boot/syslinux/syslinux.cfg                                                                                                                                                                                                                                Configure syslinux boot loaders in file:\e[0m" >> ${pacui_config}
 
-        set -u
+        #set -u
 
         # create local variables
         local {file,check}
@@ -1450,7 +1450,7 @@ function func_c
         if [[ -n "$file" ]] && (( check == 1 ))                                     # here $check variable needs to be 1 in order to continue normally and display files in a text editor.
         then
 
-            set +u                                                                  # temporarily disable strict mode for environment variables. "$EDITOR" and "$SUDO_EDITOR" variable gets used extensibely in the following code!
+            #set +u                                                                  # temporarily disable strict mode for environment variables. "$EDITOR" and "$SUDO_EDITOR" variable gets used extensibely in the following code!
 
             if [[ "$( echo "$file" | cut -c -6 )" == "/home/" ]]                    # check, if "file"'s first characters is "/home/"
             then
@@ -1494,7 +1494,7 @@ function func_c
                 sudo "${EDITOR:-/usr/bin/nano}" "$file"
             fi
 
-            set -u
+            #set -u
 
         fi
 
@@ -2081,7 +2081,7 @@ function func_help
 # pacaur sometimes does not find an editor to use and the --preview window in fzf does not show any package information.
 # instead, it shows "::editor variable unset".
 
-set +u                                                                              # temporarily disable strict mode for environment variables
+#set +u                                                                              # temporarily disable strict mode for environment variables
 
 # check, whether pacaur is installed, user config file exists, $EDITOR variable is empty, "vi" is not installed:
 if [[ -e /usr/bin/pacaur ]] && [[ ! -e $HOME/.config/pacaur/config ]] && [[ ! -n $EDITOR ]] && [[ ! -e /usr/bin/vi ]]
@@ -2091,7 +2091,7 @@ then
     echo "editor='${EDITOR:-nano}'" >> "$HOME/.config/pacaur/config"
 fi
 
-set -u
+#set -u
 
 
 # =======================
