implemented paru support cleanly. waiting for further testing before merging.

diff --git a/pacui b/pacui
--- a/pacui
+++ b/pacui
@@ -70,6 +70,10 @@ then
     then
         AUR_Helper="trizen"
 
+    elif [[ -f /usr/bin/paru ]]
+    then
+	AUR_Helper="paru"
+
     elif [[ -f /usr/bin/pacaur ]]
     then
         AUR_Helper="pacaur"
@@ -78,9 +82,6 @@ then
     then
         AUR_Helper="pamac"
 
-    elif [[ -f /usr/bin/paru ]]
-    then
-	AUR_Helper="paru"
     fi
 fi
 
@@ -163,6 +164,18 @@ function func_u
                 install_successful=false
             fi
 
+        elif [[ "$AUR_Helper" == "paru" ]]
+        then
+
+            # execute "paru --sudoloop -Syu"
+            if (paru "$argument_flag"--sudoloop -Syu --color always)
+            then
+                # only set $install_successful=true, if the command above was executed without errors
+                install_successful=true
+            else
+                install_successful=false
+            fi
+
         elif [[ "$AUR_Helper" == "pacaur" ]]
         then
 
@@ -177,26 +190,13 @@ function func_u
         then
 
             # execute "update -a" command:
-            if ( pamac "$argument_flag"update -a )                                         # execute command "update -a". if this command fails "false" is returned and the result is: "if ( false )"
+            if ( pamac "$argument_flag"update -a )                                  # execute command "update -a". if this command fails "false" is returned and the result is: "if ( false )"
             then
                 # only set $install_successful=true, if the command "update -a" was executed without errors
                 install_successful=true
             else
                 install_successful=false
-            
-	    fi
-	elif [[ "$AUR_Helper" == "paru" ]]
-        then
-
-	     # execute "paru -Syu"
-	     if (paru "$argument_flag" --sudoloop -Syu)
-	     then
-	       # only set $install_successful=true, if the command "paru -Syu" was executed without errors
-	       install_successful=true
-           else
-               install_successful=false
-
-	    fi
+            fi
 
         else
 
@@ -219,7 +219,7 @@ function func_u
 
             # if one of the above update commands has failed, there are multiple points of failure.
             # first, we can force the update, but only for packages from the system repositories and not packages from the AUR. this means, we make sure package updates from system repositories fail:
-            if ! ( sudo pacman -Syu --color always )                            # the "sudo pacman -Syu --color always" command gets executed in any case in order to check its output.
+            if ! ( sudo pacman -Syu --color always )                                # the "sudo pacman -Syu --color always" command gets executed in any case in order to check its output.
             then
 
                 # now, we are sure there is an active connection to the server/mirror/repository and package updates from there have failed. in this case, we can offer the user to forcefully install updates:
@@ -227,13 +227,13 @@ function func_u
                 # ask, whether to force update the system and save answer in "answer" variable:
                 echo -e " \e[1m Updates from system repositories have failed probably because of file conflicts. \e[0m"
                 echo -e " \e[41m Do you want to forcefully overwrite all conflicting files? [y|N] \e[0m"
-                read -r -n 1 -e answer                                          # this "read" command only accepts 1 letter as answer. this feels faster and is enough in this situation.
+                read -r -n 1 -e answer                                              # this "read" command only accepts 1 letter as answer. this feels faster and is enough in this situation.
 
-                case ${answer:-n} in                                            # if ENTER is pressed, the variable "answer" is empty. if "answer" is empty, its default value is "n".
-                    y|Y|yes|Yes|YES )                                           # do this, if "answer" is y or Y or yes or Yes or YES
+                case ${answer:-n} in                                                # if ENTER is pressed, the variable "answer" is empty. if "answer" is empty, its default value is "n".
+                    y|Y|yes|Yes|YES )                                               # do this, if "answer" is y or Y or yes or Yes or YES
                         sudo pacman -Syu --color always --overwrite='*'
                         ;;
-                    * )                                                         # do this in all other cases
+                    * )                                                             # do this in all other cases
                         echo -e " \e[1m Packages have not been updated.\e[0m"
                         ;;
                 esac
@@ -353,10 +353,10 @@ function func_m
             yay -Yc                                                                 # do orphan cleaning with yay
         elif [[ "$AUR_Helper" == "pamac" ]]
         then
-            pamac remove -o 							    # do orphan cleaning with pamac
+            pamac remove -o 							                            # do orphan cleaning with pamac
         elif [[ "$AUR_Helper" == "paru"  ]]
-	then
-	    paru -c                                                                 # do orphan cleaning with paru
+        then
+            paru -c                                                                 # do orphan cleaning with paru
         else                                                                        # do this for all other AUR helpers:
             if [[ -n "$(pacman -Qdt)" ]]                                            # only run the following commands, if output of "pacman -Qdt" is not empty.
             then
@@ -658,6 +658,10 @@ function func_i
                                 then
                                     trizen -Si {1}
 
+                                elif test '$AUR_Helper' = "paru"
+                                then
+                                    paru -Si {1} --color always | grep -v "\*\*.*\*\*"
+
                                 elif test '$AUR_Helper' = "pacaur"
                                 then
                                     pacaur -Si {1} --color always | grep -v "::"    # grep command removes all errors displayed by pacaur
@@ -665,10 +669,6 @@ function func_i
                                 elif test '$AUR_Helper' = "pamac"
                                 then
                                     pamac info -a {1}
-
-			        elif test '$AUR_Helper' = "paru"
-				then
-					paru -Si {1} | grep -v "\*\*.*\*\*"
 
                                 fi
                             fi
@@ -719,6 +719,10 @@ function func_i
             then
                 trizen "$argument_flag"-S $pkg                                      # ATTENTION: (i do not know why but) using quotes (" symbols) around $pkg variable breaks AUR helper and pacman
 
+            elif [[ "$AUR_Helper" == "paru" ]]
+            then
+                paru "$argument_flag"--color always -S $pkg                         # ATTENTION: (i do not know why but) using quotes (" symbols) around $pkg variable breaks AUR helper and pacman
+
             elif [[ "$AUR_Helper" == "pacaur" ]]
             then
                 pacaur "$argument_flag"--color always -S $pkg                       # ATTENTION: (i do not know why but) using quotes (" symbols) around $pkg variable breaks AUR helper and pacman
@@ -727,9 +731,6 @@ function func_i
             then
                 pamac "$argument_flag"install $pkg                                  # ATTENTION: (i do not know why but) using quotes (" symbols) around $pkg variable breaks AUR helper and pacman
 
-	    elif [[ "$AUR_Helper" == "paru" ]]
-            then
-	       paru "$argument_flag"-S $pkg
             else
                 sudo pacman "$argument_flag"--color always -Syu $pkg                # ATTENTION: (i do not know why but) using quotes (" symbols) around $pkg variable breaks AUR helper and pacman
 
@@ -1785,6 +1786,8 @@ function func_c
         [[ -f /etc/pakku.conf ]]                        && echo -e "/etc/pakku.conf                                                                                                                                                                                                                                                  Configure Pakku in file:" >> ${pacui_config}
         [[ -f $XDG_CONFIG_HOME/aurman/aurman_config ]]  && echo -e "$XDG_CONFIG_HOME/aurman/aurman_config                                                                                                                                                                                                                            Configure Aurman in file:" >> ${pacui_config}
         [[ -f $HOME/.config/aurman/aurman_config ]]     && echo -e "$HOME/.config/aurman/aurman_config                                                                                                                                                                                                                               Configure Aurman in fallback file:" >> ${pacui_config}
+        [[ -f $XDG_CONFIG_HOME/paru/paru.conf ]]        && echo -e "$XDG_CONFIG_HOME/paru/paru.conf                                                                                                                                                                                                                                  Configure Paru in file:" >> ${pacui_config}
+        [[ -f $HOME/.config/paru/paru.conf ]]           && echo -e "$HOME/.config/paru/paru.conf                                                                                                                                                                                                                                     Configure Paru in file:" >> ${pacui_config}
         [[ -f /etc/pamac.conf ]]                        && echo -e "/etc/pamac.conf                                                                                                                                                                                                                                                  Configure Pamac in file:" >> ${pacui_config}
         [[ -f /etc/makepkg.conf ]]                      && echo -e "/etc/makepkg.conf                                                                                                                                                                                                                                                Configure package compilation in file:" >> ${pacui_config}
         [[ -d /usr/lib/NetworkManager/conf.d ]]         && echo -e "/usr/lib/NetworkManager/conf.d/                                                                                                                                                                                                                                  Configure NetworkManager in files:" >> ${pacui_config}
@@ -2026,6 +2029,10 @@ function func_ua
         then
             trizen "$argument_flag"-Syu --devel --needed
 
+        elif [[ "$AUR_Helper" == "paru" ]]
+        then
+            paru "$argument_flag"-Syu --devel --needed --color always
+
         elif [[ "$AUR_Helper" == "pacaur" ]]
         then
             pacaur "$argument_flag"-Syua --devel --needed --color always
@@ -2034,9 +2041,6 @@ function func_ua
         then
             pamac "$argument_flag"update -a --devel
 
-        elif [[ "$AUR_Helper" == "paru" ]]
-	then
-            paru "$argument_flag"-Syu --devel --needed
         else
             echo -e " \e[41m No AUR helper has been found. Please install at least one supported AUR helper manually: \e[0m"
             echo -e " \e[1m  yay \e[0m"
@@ -2044,9 +2048,9 @@ function func_ua
             echo -e " \e[1m  aurman \e[0m"
             echo -e " \e[1m  pakku \e[0m"
             echo -e " \e[1m  trizen \e[0m"
+            echo -e " \e[1m  paru \e[0m"
             echo -e " \e[1m  pacaur \e[0m"
             echo -e " \e[1m  pamac \e[0m"
-	    echo -e " \e[1m  paru \e[0m"
 
         fi
 }
@@ -2100,6 +2104,10 @@ function func_la
                 then
                     trizen -Si {1}
 
+                elif test '$AUR_Helper' = "paru"
+                then
+                    paru -Si {1} --color always | grep -v "\*\*.*\*\*"
+
                 elif test '$AUR_Helper' = "pacaur"
                 then
                     pacaur -Si {1} --color always | grep -v "::"                    # grep command removes all errors displayed by pacaur
@@ -2107,9 +2115,6 @@ function func_la
                 elif test '$AUR_Helper' = "pamac"
                 then
                     pamac info -a {1}
-	        elif test '$AUR_Helper' = "paru"
-		then
-		    paru -Si {1} | grep -v "\*\*.*\*\*"
 
                 fi
             fi
@@ -2206,6 +2211,10 @@ function func_a
             then
                 trizen "$argument_input"
 
+            elif [[ "$AUR_Helper" == "paru" ]]
+            then
+                paru "$argument_input" --color always
+
             elif [[ "$AUR_Helper" == "pacaur" ]]
             then
                 pacaur -Ss "$argument_input" --color always | grep -v "::"          # grep command removes errors being displayed in pacaur
@@ -2214,10 +2223,6 @@ function func_a
             then
                 pamac search -a "$argument_input"
 
-	    elif [[ "$AUR_Helper" == "paru" ]]
-	    then
-		paru "$argument_input"
-
             else
                 echo -e " \e[41m No AUR helper has been found. Please install at least one supported AUR helper manually: \e[0m"
                 echo -e " \e[1m  yay \e[0m"
@@ -2225,9 +2230,9 @@ function func_a
                 echo -e " \e[1m  aurman \e[0m"
                 echo -e " \e[1m  pakku \e[0m"
                 echo -e " \e[1m  trizen \e[0m"
+                echo -e " \e[1m  paru \e[0m"
                 echo -e " \e[1m  pacaur \e[0m"
                 echo -e " \e[1m  pamac \e[0m"
-		echo -e " \e[1m  paru \e[0m"
 
             fi
 
@@ -2257,6 +2262,10 @@ function func_a
             then
                 trizen "$pkg"
 
+            elif [[ "$AUR_Helper" == "paru" ]]
+            then
+                paru "$pkg" --color always
+
             elif [[ "$AUR_Helper" == "pacaur" ]]
             then
                 pacaur -Ss "$pkg" --color always | grep -v "::"                     # grep command removes errors being displayed in pacaur
@@ -2265,10 +2274,6 @@ function func_a
             then
                 pamac search -a "$pkg"
 
-	    elif [[ "$AUR_Helper" == "paru" ]]
-	    then
-		paru "$pkg"
-
             else
                 echo -e " \e[41m No AUR helper has been found. Please install at least one supported AUR helper manually: \e[0m"
                 echo -e " \e[1m  yay \e[0m"
@@ -2276,9 +2281,9 @@ function func_a
                 echo -e " \e[1m  aurman \e[0m"
                 echo -e " \e[1m  pakku \e[0m"
                 echo -e " \e[1m  trizen \e[0m"
+                echo -e " \e[1m  paru \e[0m"
                 echo -e " \e[1m  pacaur \e[0m"
                 echo -e " \e[1m  pamac \e[0m"
-		echo -e " \e[1m  paru \e[0m"
 
             fi
 
@@ -2299,7 +2304,7 @@ function func_help
 
 \e[1mWelcome to PacUIs Help Page
 
-PacUI is an interactive package manager for your command line terminal. It provides an easy user interface and uses Pacman and Yay/Pikaur/Aurman/Pakku/Trizen/Pacaur as back ends.
+PacUI is an interactive package manager for your command line terminal. It provides an easy user interface and uses Pacman and Yay/Pikaur/Aurman/Pakku/Trizen/Paru/Pacaur/Pamac-cli as back ends.
 
 Navigate this help page with your Arrow Keys, PageUp/PageDown Keys, SpaceBar, or your Mouse Wheel. To search this Help Page, enter /<SEARCH TERM> and press ENTER. For example, enter the following (without quotes " ") in order to search for the word "update": "/update". Press N key to continue searching for other occurrences of "update". Search is not case sensitive. To exit this Help Page, press your Q key.
 PacUI uses Fuzzy Finder (fzf) to display selectable lists, which can be easily searched by starting to type. Advanced users can even utilize regular expressions for it. Navigate fzf's list the same way you navigate this help page.
@@ -2468,7 +2473,7 @@ This command deletes all PacUI files in /tmp directory. PacUI uses this temporar
 
 \e[36m"sudo unlink /var/lib/pacman/db.lck"
 This command removes Pacmans database lock. The database lock prevents multiple Pacman instances from running at the same time and interfering with each other.
-\e[1mAttention\e[0m: Only run this command when no other Pacman instance (e.g. Pacman, Pamac, Octopi, PacmanXG4, Yay, Pikaur, Aurman, Pakku, Trizen, Pacaur, ...) is running.
+\e[1mAttention\e[0m: Only run this command when no other Pacman instance (e.g. Pacman, Pamac, Octopi, PacmanXG4, Yay, Pikaur, Aurman, Pakku, Trizen, Paru, Pacaur, Pamac-cli ...) is running.
 
 \e[36m"sudo pacman-mirrors -f 0 && sudo pacman -Syy" \e[0m(for Manjaro)
 This command generates a new mirrorslist of all available Manjaro repository mirrors/servers and sorts it by ping of up-to-date mirrors/servers. Additionally, the latest package database is downloaded from the chosen Manjaro repository mirror. If you want to speed up this command, it is recommended to only test your connection quality to Manjaro mirrors/servers near you. Example: You have noticed the pings to German and French mirrors are always best for you. Then, you can run: "sudo pacman-mirrors -c Germany,France".
