new 'install' option

diff --git a/pacui b/pacui
--- a/pacui
+++ b/pacui
@@ -348,106 +348,83 @@ function func_i
         if [[ -n $pkg ]]
         then
 
+            # define local variable, which indicates whether the installation process was successful or not.
+            local install_successful
+
             if [[ ! -e /usr/bin/pacaur ]]                                           # checks, whether file "pacaur" does not exist
             then
-                yaourt -S $pkg_install                                              # !!! this command does not work when $pkg_install is quoted !!! (i do not know why)
-            else
-                pacaur -S $pkg_install --color always
-            fi
 
-        fi
-}
-
-
-# Force Install Packages
-# this core functionality of "Force Install Packages" (note the bold "f" and "i") can be started in the terminal using "pacui fi". the help page provides additional explanations.
-function func_fi
-{
-        # check, whether file /tmp/pacui-packages-group-repo already exists (the ! negates the result)
-        if [[ ! -e /tmp/pacui-packages-group-repo ]]
-        then
-            # write formatted package list of repositories to /tmp/pacui-packages-group-repo. then add all package groups to the bottom.
-            #pacman -Slq | tr -d " " > /tmp/pacui-packages-group-repo
-            expac -S "%-33n\t%d"  > /tmp/pacui-packages-group-repo
-            #pacman -Sg | tr -d " " >> /tmp/pacui-packages-group-repo
-            expac -Sg %G | sort -u | sed 's/ /\n/g' | sort -u | awk 'NF != 0' >> /tmp/pacui-packages-group-repo
-        fi
-
-        local {pkg,pkg_install}
-
-        pacui_clean                                                                 # clear terminal
-
-        # take a sorted package (and group) list from /tmp/pacui-packages-group, then make the resulting list available to fzf.
-        # fzf lets you search and select the given list in a fast way. the "-m" flags makes it possible to select multiple list items.
-        # the --preview option of fzf displays information about the currently selected line
-        pkg=$( sort -k1,1 -u /tmp/pacui-packages-group-repo | fzf-tmux -m -e +s -i -1 --query="$input2" --cycle --reverse --margin=4%,1%,1%,2% --inline-info --preview '
-            if ( pacman -Qq {1} &>/dev/null )                                       # check, if selected line is a locally installed package
-            then
-                pacman -Qi {1} --color always
-            elif ( pacman -Sgq {1} &>/dev/null )                                    # check, if selected line in fzf is a package group
-            then
-                echo -e "\e[1m{1} group has the following members: \e[0m"
-                pacman -Sgq {1}
-            else                                                                    # do this if line is neither a group nor locally installed
-                if [[ ! -e /usr/bin/pacaur ]]                                       # checks, whether file "pacaur" does not exist
+                # execute "yaourt -S $pkg_install" command:
+                if ( yaourt -S $pkg_install )                                       # !!! this command does not work when $pkg_install is quoted !!! (i do not know why)
                 then
-                    yaourt -Si {1}
+                    # only set $install_successful=true, if the command "yaourt -S $pkg_install" was executed without errors
+                    install_successful=true
                 else
-                    pacaur -Si {1} --color always | grep -v "::"                    # grep command removes errors being displayed in pacaur
+                    install_successful=false
                 fi
+            
+            else
+
+               # execute "pacaur -S $pkg_install --color always" command:
+                if ( pacaur -S $pkg_install --color always )
+                then
+                    # only set $install_successful=true, if the command "pacaur -S $pkg_install --color always" was executed without errors
+                    install_successful=true
+                else
+                    install_successful=false
+                fi
+
             fi
-            ' --preview-window=right:50%:wrap  --header="TAB key to (un)select. ENTER key to install. ESC to quit." --prompt='Enter string to filter list > ' | awk '{print $1}' )
 
-        pacui_clean                                                                 # clear terminal
 
-        # $pkg contains package names below each other, but we need a list (in 1 line, space separated):
-        pkg_install=$(echo $pkg | paste -sd " ")
-
-        if [[ -n $pkg ]]                                                            # check, whether variable $pkg is empty - this happens when fzf is quit with ESC or CTRL+C
-        then
-            sudo pacman -S --force $pkg_install --color always
-        fi
-}
-#------------------------------
-                # ask, whether to remove the displayed orphaned packages and save answer in "answer" variable:
-                read -p $'\e[1mDo you want to remove these orphaned packages? [Y|n]\e[0m' answer
-                case ${answer:-y} in                                                # if ENTER is pressed, the variable "answer" is empty. if "answer" is empty, its default value is "y".
-                    y|Y|yes|YES|Yes )                                               # do this, if "answer" is y or Y or yes or YES or Yes
-                        sudo pacman -Rsn $(pacman -Qqdt) --color always --noconfirm
-                        ;;
-                    * )                                                             # do this in all other cases
-                        echo "Packages have not been removed."
-                        ;;
-                esac   
-
-#------------------------------------
-            # wrap the "sudo pacman -Rns" command in an if-statement, which checks, whether the removal of packages works. the removal of packages does not work, if the user tries to remove a dependency.
-            # the failure of "sudo pacman -Rns" is especially annoying, if many packages has been chose for removal and 1 package is a dependency. by default, the list of pacakges (which are supposed to be removed) is NOT saved!
-            # "sudo pacman -Rsn $pkg_remove --color always" always gets executed!
-            if ! ( sudo pacman -Rsn $pkg_remove --color always )
+            # if one of the above installation commands has failed, the following if-statement is true:
+            if [[ $install_successful == "false" ]]
             then
 
-                # continue here only if "sudo pacman -Rns" has failed:
-                # 1. save list of packages to backup file.
-                echo $pkg_remove | tr " " "\n" > /tmp/pacui-remove-backup           # tr " " "\n" is needed to convert the list of package names (in 1 line) back to multiple lines. otherwise, fzf cannot work with it.
+                # because it is possible the installation of AUR packages has failed (and we cannot do anything to solve this automatically), we have to check, whether installation from the system repositories fails:
+                if ! ( sudo pacman -S $pkg_install --color always )
+                then
 
+                    # check, whether there is a connection to the mirror/repository server. this is needed for package installation!
+                    if ( sudo pacman -Syy )                                                 # the "sudo pacman -Syy" command gets executed in any case in order to check its output.
+                    then
 
+                        # now, we can be sure that installation of a package from the system repositories has failed. Print error message below the error output of pacman.
+                        echo
+                        echo -e "\e[1mPackage installation has failed most likely because of file conflicts.\e[0m"
+                        echo -e "\e[1mDo you want to forcefully install and overwrite all selected packages anyway? [y|N]\e[0m"
+                        # save answer in "answer" variable:
+                        read -r answer
 
+                        case ${answer:-n} in                                                # if ENTER is pressed, the variable "answer" is empty. if "answer" is empty, its default value is "n".
+                            y|Y|yes|YES|Yes )                                               # do this, if "answer" is y or Y or yes or YES or Yes
+                                sudo pacman -S --force $pkg_install --color always
+                                ;;
+                            * )                                                             # do this in all other cases
+                                echo "Installation process has been cancelled."
+                                ;;
+                        esac
 
+                    else
 
+                        # print error message, if there is no connection to a mirror/repository server and quit 
 
+                        local server
+                        # extract mirror/repository server url from /etc/pacman.d/mirrorlist file:
+                        server=$( grep "^Server =" -m 1 /etc/pacman.d/mirrorlist | awk '{print $3}' )
 
+                        echo -e "\e[41m Either there is something wrong with your internet connection or with your mirror/repository server: "$server" \e[0m"
+                        echo -e "\e[1;41m Please make sure both are ok and rerun this part of PacUI! \e[0m"
+                        echo -e ""
 
+                    fi
 
+                fi
+            
+            fi
 
-
-
-
-
-
-
-
-
+        fi
+}
 
 
 # Remove Packages
@@ -493,7 +470,7 @@ function func_r
                 # now, "sudo pacman -Rsn $pkg_remove --color always" has failed. this means that a dependency was selected. Print error message below the error output of pacman.
                 echo
                 echo -e "\e[1mPackage removal failed because at least one dependency was selected.\e[0m"
-
+                echo
                 echo -e "\e[1mDo you want to forcefully remove all selected packages anyway? [y|N]\e[0m"
                 echo -e "\e[1mChoose one of the following options: \e[0m"
                 echo
